### PR TITLE
Html consistency (double quotes)

### PR DESCRIPTION
**Pull request by mauriciosoares**
Hey there,

For some reason there were some times you were using double quotes and others you were not on the HTML guidelines...

I don't know if that was on purpose, but in case it was not, here goes a PR fixing all the occasions that it happened. Otherwise just reject this PR. :)

Great guideline.

### CODE REVIEW

**Comment by technofreaky** [comment]
+1

**Comment by jdhartley** [comment]
:+1:

**Comment by Ace80** [comment]
*bad*

**Comment by gpedro** [comment]
:+1:

**Comment by anEffingChamp** [comment]
There is no thing wrong with a consistent style guide for a document, but double quotes, single quotes, and in many cases no quotes are equally standards compliant. The general tone of this repository seems to be taking advantage of standards, so either way is OK. I am not criticizing you though, so good catch on the quotation.

**Pull request closed without merging**
