### PR TITLE
Add semicolon

### PR DESCRIPTION
**Pull request by GauriAarjariya**

### CODE REVIEW

**Comment by GauriAarjariya** [comment]
i know that ading a semicolon is not a big deal but when a code is in place , it shoul be good for reading

**Comment by bendc** [comment]
Adding a semicolon there is invalid js.

**Comment by GauriAarjariya** [comment]
Ohk... Actually I am participating in Hactober fest and this is my first
pull request but that is OK if you can't accept it😊😊

**Comment by misbeliever** [comment]
@gauriarjariyacodingclub you broke the function with your PR, please check before PR

**Pull request closed without merging**
