### PR TITLE
fix Map() example

### PR DESCRIPTION
**Pull request by pruett**
use the 'new' operator within Map() example

### CODE REVIEW

**Comment by bendc** [comment]
Why?

**Comment by NET4ORCE** [comment]
Some engines throw on var m = Map();

**Comment by pruett** [comment]
I was playing around with babel's REPL [http://babeljs.io/repl/](http://babeljs.io/repl/) to acquaint myself with `Map`, it barked at me when I didn't use the new operator, so I thought it'd be useful to readers diving into the syntax for the first time.

Really enjoyed the writeup @bendc

**Comment by bendc** [comment]
Thanks @pruett!

Omitting `new` is a personal preference really, I don't think there's a good argument for using it or not. I'll keep it like this unless there's something I missing :)

**Comment by condemoreloer** [comment]
https://github.com/showcases/open-source-organizations

**Pull request closed without merging**
